services:
  web:
    container_name: movie
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER_NAME: ${DATABASE_USER_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/usr/src/app
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/data
  sidekiq:
    container_name: sidekiq
    build:
      context: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - '.:/usr/src/app'
      - '.:/usr/src/app/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - movie
    ports:
      - '8020:8020'
volumes:
  db_data:
  redis_data:
  bundle:
