services:
  web:
    container_name: web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    depends_on:
      - db
      - redis
  db:
    container_name: db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/data
  sidekiq:
    container_name: sidekiq
    build:
      context: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - '.:/app'
      - '/app/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    depends_on:
      - web
    ports:
      - '8020:8020'
volumes:
  pg_data:
  redis_data:
  bundle:
