
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: databasepass
  # host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: booking_system_dev
  # username:  <%= ENV['DATABASE_USER_NAME'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: booking_system_test

production:
  <<: *default
  # url: <%= ENV['DATABASE_URL'] %>
  database: booking_system
