// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
// import "@hotwired/turbo-rails"
import "jquery"
import "jquery_rails"
import "jquery_ujs"
import "popper"
import "bootstrap"
import "trix"
import "@fortawesome/fontawesome-free"
import "@rails/actiontext"
import "mixitup"
import "owl.carousel"
import "slicknav"
import "toastr"
import "mixi"
import "player"
import "nice-select"
import "controllers"
import "window-load"
import "custom"
import "admin"
import "main-layout"
